---
title: "Exécuter un plan d'analyse"
author: "Martin Barner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running an analysis plan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(knitr)
setwd("../.")
getwd()



```


### Charger package
```{r,warning=FALSE,message=FALSE,error=FALSE}
library(hypegrammaR)
library(dplyr)
```
### Preparer les données



### Charger les données
Pour plus de details veuillez s'il-vous-plait regarder <a href="input_formats.html">Format d'entrée et charger fichiers</a>

```{r,warning=F,message=F,error=F}
assessment_data<-load_data("../tests/testthat/testdata.csv")
```

```{r,warning=F,message=F,error=F}
samplingframe<-load_samplingframe("../tests/testthat/test_samplingframe.csv")
```

```{r,warning=F,message=F,error=F}
weights<-map_to_weighting(sampling.frame = samplingframe,
                          data.stratum.column = "stratification",
                          sampling.frame.population.column = "population",
                          sampling.frame.stratum.column = "strata names",
                          data = assessment_data)
```

```{r,warning=F,message=F,error=F}

questionnaire<-load_questionnaire(data = assessment_data,
                                  questions.file = "../tests/testthat/kobo questions.csv",
                                  choices.file = "../tests/testthat/kobo choices.csv",
                                  choices.label.column.to.use = "label::English"
)
```

```{r,warning=F,message=F,error=F}

analysisplan<-load_analysisplan("../tests/testthat/analysisplan.csv")

```

### Exécuter le plan d'analyse et enregistrer les sorties sous forme de fichier html

```{r,eval = F}
list_of_results<- assessment_data %>%   from_analysisplan_map_to_output(analysisplan = analysisplan,
                                                                        weighting = weights,
                                                                        questionnaire = questionnaire) 

  
```

### Sortie en html
```{r,eval = F}

list_of_results %>% map_to_template(questionnaire = questionnaire,
                                    dir = "../",
                                    filename = "my_example_report.html")

```



